AutismAppointmentApp.WebMVC/Controllers/PatientController/PatientController.cs
using AutismAppointmentApp.Models.PatientModels;
using AutismAppointmentApp.Services.PatientServices;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace AutismAppointmentApp.WebMVC.Controllers.PatientController
{
    [Authorize]
    public class PatientController : Controller
    {
        private readonly IPatientService _service;

        public PatientController(IPatientService service)
        {
            _service = service;
        }

        // GET: Patient
        public ActionResult Index()
        {
            var model = _service.GetAllPatients(User.Identity.GetUserId());
            return View(model);
        }

        // GET: Patient/Create
        public ActionResult Create()
        {
            return View();
        }

        //POST: Patient/Create
        [HttpPost]
        [AcceptVerbs(HttpVerbs.Post)]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PatientCreate model, HttpPostedFileBase file)
        {
            if (!ModelState.IsValid)
                return View(model);

            model.UserId = User.Identity.GetUserId();

            string rootedPath;
            string path = " ";
            string fileName;

            if (file != null)
            {
                fileName = Path.GetFileName(file.FileName);
                path = "/Content/img/" + fileName;

                rootedPath = Path.Combine(Server.MapPath("~/Content/img"), fileName);
                file.SaveAs(rootedPath);
            }

            if (_service.CreatePatient(model, path))
            {

                TempData["SaveResult"] = "The patient was added successfully.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "The patient could not be added... Try again later.");
            return View(model);
        }

        // GET: Patient/{id}
        public ActionResult Details(int id)
        {
            var model = _service.GetPatientById(id, User.Identity.GetUserId());

            if (model == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            return View(model);
        }

        // GET: Patient/Delete/{id}
        [ActionName("Delete")]
        public ActionResult Delete(int id, string path)
        {
            var model = _service.GetPatientById(id, User.Identity.GetUserId());
            return View(model);
        }

        // POST: Patient/Delete/{id}
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Delete")]
        public ActionResult DeletePost(int id)
        {
            _service.DeletePatient(id, User.Identity.GetUserId());
            TempData["SaveResult"] = "The patient was deleted successfully.";
            return RedirectToAction("Index");
        }

        //GET: Patient/Edit/{id}
        public ActionResult Edit(int id, string path)
        {
            var entity = _service.GetPatientById(id, User.Identity.GetUserId());
            var model =
                new PatientEdit
                {
                    PatientId = entity.PatientId,
                    FirstName = entity.FirstName,
                    LastName = entity.LastName,
                    Gender = entity.Gender,
                    Address = entity.Address,
                    TherapyNeeded = entity.TherapyNeeded,
                    HasTherapy = entity.HasTherapy
                };

            if (model == null)
                return HttpNotFound();

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, PatientEdit model)
        {
            if (!ModelState.IsValid)
                return View(model);

            if (model.PatientId != id)
            {
                ModelState.AddModelError("", "ID does not match.");
                return View(model);
            }

            model.UserId = User.Identity.GetUserId();

            if (_service.UpdatePatient(model))
            {
                TempData["SaveResult"] = "The patient was updated.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "The patient could not be updated... Try again later.");
            return View(model);
        }
    }
}

AutismAppointmentApp.WebMVC/Controllers/TherapistController/TherapistController.cs
using AutismAppointmentApp.Models.TherapistModels;
using AutismAppointmentApp.Services.TherapistServices;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AutismAppointmentApp.WebMVC.Controllers.TherapistController
{
    [Authorize]
    public class TherapistController : Controller
    {
        private readonly ITherapistService _service;

        public TherapistController(ITherapistService service)
        {
            _service = service;
        }

        // GET: Therapist
        public ActionResult Index()
        {
            var model = _service.GetAllTherapists(User.Identity.GetUserId());
            return View(model);
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [AcceptVerbs(HttpVerbs.Post)]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TherapistCreate model, HttpPostedFileBase file)
        {
            if (!ModelState.IsValid)
                return View(model);

            model.UserId = User.Identity.GetUserId();

            string rootedPath;
            string path = " ";
            string fileName;

            if (file != null)
            {
                fileName = Path.GetFileName(file.FileName);
                path = "/Content/img/" + fileName;

                rootedPath = Path.Combine(Server.MapPath("~/Content/img"), fileName);
                file.SaveAs(rootedPath);
            }

            if (_service.CreateTherapist(model, path))
            {
                TempData["SaveResult"] = "The therapist was added successfully.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "The therapist could not be added... Try again later.");
            return View("Index");
        }

        public ActionResult Details(int id)
        {
            var model = _service.GetTherapistById(id, User.Identity.GetUserId());
            return View(model);
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var entity = _service.GetTherapistById(id, User.Identity.GetUserId());
            var model =
                new TherapistEdit
                {
                    TherapistId = entity.TherapistId,
                    FirstName = entity.FirstName,
                    LastName = entity.LastName,
                    TherapySpecialist = entity.TherapySpecialist,
                    IsCertified = entity.IsCertified
                };

            return View(model);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, TherapistEdit model)
        {
            if (!ModelState.IsValid)
                return View(model);

            if (model.TherapistId != id)
            {
                ModelState.AddModelError("", "ID does not match.");
                return View(model);
            }

            model.UserId = User.Identity.GetUserId();

            if (_service.UpdateTherapist(model))
            {
                TempData["SaveResult"] = "The therapist was updated.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "The therapist could not be updated... Try again later. ");
            return View(model);
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var model = _service.GetTherapistById(id, User.Identity.GetUserId());
            return View(model);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Delete")]
        public ActionResult DeletePost(int id)
        {
            _service.DeleteTherapist(id, User.Identity.GetUserId());
            TempData["SaveResult"] = "The therapist was deleted successfully.";
            return RedirectToAction("Index");
        }
    }
}

AutismAppointmentApp.WebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Autism Appointment Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <nav class="navbar @*navbar-expand-lg*@ navbar-dark bg-primary">
        <div class="container-fluid">
            <a class="navbar-brand" href="@Url.Action("Index", "Home")">Home</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "Patient")">Current Patients</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Create", "Patient")">Add a Patient</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "Therapist")">Active Therapists</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Create", "Therapist")">Add a Therapist</a>
                    </li>
                    <div class="dropdown-divider"></div>
                    <li class="nav-item">
                        @*<a class="nav-link" href="@Url.Action("Login", "Account")">Log in</a>*@
                        @Html.Partial("_LoginPartial")
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="navbar-collapse collapse">
        @*<ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("About", "About", "Home")</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
            </ul>*@
        @*@Html.Partial("_LoginPartial")*@
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Autism Appointment Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>